export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const INCREASE_PRODUCT = "INCREASE_PRODUCT";
export const DECREASE_PRODUCT = "DECREASE_PRODUCT";
export const CHANGE_PRODUCT_IMAGES = "CHANGE_PRODUCT_IMAGES";
export const IMAGES_MOBILE_NEXT = "IMAGES_MOBILE_NEXT";
export const IMAGES_MOBILE_PREV = "IMAGES_MOBILE_PREV";
export const LIGHTBOX_OPEN = "LIGHTBOX_OPEN";
